FROM astj/centos5-vault
MAINTAINER Chad Barraford <chad@rstudio.com>

RUN yum -y update
RUN yum -y install epel-release
RUN yum -y groupinstall "Development tools"
RUN yum -y install rsyslog screen passwd sudo wget git python26 python-setuptools python-devel gcc glibc-devel python-setuptools R curl openssl-devel
RUN easy_install Mercurial==3.4.2

RUN cd /usr/local/ && \
    wget -O jdk.tar.gz --no-cookies --no-check-certificate --header "Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie" "http://download.oracle.com/otn-pub/java/jdk/8u141-b15/336fa29ff2bb4ef291e347e091f7f4a7/jdk-8u141-linux-x64.tar.gz" && \
    tar xzf jdk.tar.gz && \
    cd /usr/local/jdk1.8.0_141/ && \
    alternatives --install /usr/bin/java java /usr/local/jdk1.8.0_141/bin/java 2 && \
    alternatives --install /usr/bin/jar jar /usr/local/jdk1.8.0_141/bin/jar 2 && \
    alternatives --install /usr/bin/javac javac /usr/local/jdk1.8.0_141/bin/javac 2 && \
    alternatives --set jar /usr/local/jdk1.8.0_141/bin/jar && \
    alternatives --set javac /usr/local/jdk1.8.0_141/bin/javac && \
    rm /usr/local/jdk.tar.gz

# need to run a recent openssl to get SAN support for when we compile wget
RUN wget http://www.openssl.org/source/openssl-1.0.2j.tar.gz \
    && tar xvf openssl-1.0.2j.tar.gz \
    && cd openssl-1.0.2j \
    && make clean \
    && ./config shared --prefix=/usr --openssldir=/usr/local/openssl \
    && make && make install

# Get a new wget to avoid a bug with wildcard certs; but not so new that it
# passes --utf8 to pod2man
#
# DO NOT remove the RedHat wget, as later installs may attempt to use yum to
# fetch/update it. Rely on /usr/local/bin being before /usr/bin in the PATH.
RUN wget http://ftp.gnu.org/gnu/wget/wget-1.19.1.tar.gz && \
    tar xzvf wget-1.19.1.tar.gz && \
    cd wget-1.19.1 && \
    ./configure --with-ssl=openssl --with-libssl-prefix=/usr/lib64/openssl --prefix=/usr/local && \
    make && make install

# UPDATE THE CERTS. TRUST THE HAXX.
RUN wget --no-check-certificate -O /etc/pki/tls/certs/ca-bundle.crt https://curl.haxx.se/ca/cacert.pem

# install cmake
RUN curl -Lk http://www.cmake.org/files/v2.8/cmake-2.8.10.tar.gz | tar xz && cd cmake-2.8.10 && ./configure && make && make install

RUN wget --no-check-certificate https://people.centos.org/tru/devtools-2/devtools-2.repo -O /etc/yum.repos.d/devtools-2.repo
RUN yum -y install devtoolset-2-gcc devtoolset-2-binutils
RUN yum -y install devtoolset-2-gcc-gfortran devtoolset-2-gcc-c++

# create jenkins user, make sudo. try to keep this toward the bottom for less cache busting
ARG JENKINS_GID=999
ARG JENKINS_UID=999
RUN groupadd -g $JENKINS_GID jenkins && \
    useradd -m -d /var/lib/jenkins -u $JENKINS_UID -g jenkins jenkins && \
    echo "jenkins ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
