# Dev mode configuration for shiny-server
# Run from the project root: npm run dev

run_as :PROCESS_USER:;
socket_dir ./dev/sockets;
bookmark_state_dir ./dev/bookmarks;

server {
  listen 3838;

  location / {
    site_dir ./dev/apps;
    log_dir ./dev/log;
    directory_index on;
    python .venv/;
  }
}
