#!/bin/sh
#
# chkconfig:   2345 80 20 
# description: shiny-server deploys R shiny applications
# processname: shiny-server

# Source function library.
. /etc/rc.d/init.d/functions

prog=shiny-server

# Exit if the package is not installed
[ -x "$rserver" ] || exit 0

start() {
    echo -n $"Starting shiny-server: "
    daemon $rserver
    retval=$?
    echo
    [ $retval -eq 0 ] && touch $lockfile
    return $retval
}

stop() {
    echo -n $"Stopping shiny-server: "
    killproc $prog
    retval=$?
    echo
    [ $retval -eq 0 ] && rm -f $lockfile
    return $retval
}

restart() {
    stop
    sleep 1
    start
}

rh_status() {
    status $prog
}

rh_status_q() {
    rh_status >/dev/null 2>&1
}

case "$1" in
    start)
        rh_status_q && exit 0
        $1
        ;;
    stop)
        rh_status_q || exit 0
        $1
        ;;
    restart)
        $1
        ;;
    status)
        rh_status
        ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart}"
        exit 2
esac

